# Generated by Django 4.2.11 on 2024-04-01 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arepas_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arepa',
        ),
    ]
