# Generated by Django 4.2.11 on 2024-04-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arepas_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arepa',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
