# Generated by Django 4.2.11 on 2024-04-09 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_pedido', models.CharField(max_length=10, unique=True)),
                ('bloque', models.CharField(max_length=6)),
                ('fecha_orden', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True)),
                ('cliente', models.CharField(max_length=50)),
                ('referencia', models.CharField(max_length=50)),
                ('total_pares', models.IntegerField(editable=False)),
                ('foto_orden', models.ImageField(blank=True, upload_to='ordenes/')),
            ],
            options={
                'db_table': 'orden_pedido',
            },
        ),
        migrations.CreateModel(
            name='ListaPares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(choices=[('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41')], max_length=2)),
                ('pares', models.IntegerField(default=0)),
                ('orden_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_pares', to='ordenes_app.ordenpedido')),
            ],
            options={
                'db_table': 'lista_pares',
            },
        ),
    ]
